### ISSUE TITLE
[rollup-plugin-dynamic-import-variables] Unexpected token at blank position

### ISSUE THREAD

**Issue by asasvirtuais** [LarsDenBakker/rollup-plugin-dynamic-import-variables#12]
Using @vitejs, I did not add this @rollup plugin to my project, but I got this new error when trying to build.

```
[rollup-plugin-dynamic-import-variables] Unexpected token (4:29)
file: /root/modules/app/main.tsx:4:29
```

**main.tsx **

```typescript
import { StrictMode } from 'react'
import { render } from 'react-dom'
import { ChakraProvider } from '@chakra-ui/react'
                            <- Here is 4:29 
```

**Comment by asasvirtuais** [comment]
The wonderful land of JavaScript tooling

**Comment by asasvirtuais** [comment]
THE WONDERFUL WORLD OF JAVASCRIPT TOOLING

MY @vitejs config file had the following


**vite.config.ts**

```typescript
export default defineConfig( {
                 // yada yada
 		
 		define: {
			asas: {
				BugsnagPublicKey : config.BugsnagPublicKey,
			}
               }

 })
```

And guess what by changing the name of the global defined asas to AsasVirtuais everything went back to normal.

How does a global defined variable makes the rollup-plugin-dynamic-import-variables break and tell you that blank spaces on your code are unexpected tokens? Only GOD knows.

**Comment by hikariNTU** [comment]
This has nothing to do with this plugin. Vite replace the string directly as it.
[Configuring Vite | Vite #define](https://vitejs.dev/config/#define)
Read the Vite define part carefully, it said it **replace the string** directly in your source code. 

So you will probably want to define a more complicated symbol for it.

eg. `{ '__GLOBAL_ASAS__': config.BugsnagPublicKey }`

And I don't think passing an object will be a good idea since it's not documented.

An example of define the package version:
```jsx
// vite.config.js
export default defineConfig({
  define: {
    __PLUGIN_VERSION__: JSON.stringify(process.env.npm_package_version),
  },
})

// env.d.ts
/** Need a declaration file to define it */
declare const __PLUGIN_VERSION__: string

// Something.jsx
const version = __PLUGIN_VERSION__

export default () => <span>{ version }</span>
```
